version: "3"
services:
  php:
     build:
       context: .
       dockerfile: ./data/php/Dockerfile
       args:
           TIMEZONE: ${TIMEZONE}
     volumes:
       - ./data/php:/var/www/certbot/phpDir/:rw
       - ./data/certbotSymfony/www:/var/www/certbot/

     expose:
       - 9000
     networks:
       - default
  nginx:
     image: nginx:1.15-alpine
     expose:
       - "80"
       - "443"
     ports:
       - "80:80"
       - "443:443"
     networks:
       - default
     volumes:
       - ./data/nginx:/etc/nginx/conf.d/:rw
       - ./data/certbot/conf:/etc/letsencrypt/:rw
       - ./data/certbotSymfony/conf:/etc/letsencrypt/symfony/:rw
       - ./data/certbotSymfony/www:/var/www/certbot/:rw
     command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  db:
     image: postgres:13
     volumes:
       - db-data:/var/lib/postgresql/data/pgdata
#       - db-data:/var/www/certbot/:rw
#       - db-data:/var/www/certbot/phpDir/symfony/escapalmiSymfony/public/:rw
     ports:
       - 5432:5432/tcp
     environment:
       - POSTGRES_PASSWORD=pg_pass
       - POSTGRES_USER=pg_user
       - POSTGRES_DB=pg_db_name
       - PGDATA=/var/lib/postgresql/data/pgdata
  web:
     image: odoo:13.0
     depends_on:
       - db
     ports:
       - "8069:8069/tcp"
     volumes:
       - web-data:/var/lib/odoo
#       - web-data:/var/www/certbot/phpDir/Odoo:rw
       - ./data/odoo/config:/etc/odoo
       - ./data/odoo/addons:/mnt/extra-addons
#       - web-data:/var/www/certbot/phpDir/symfony/escapalmiSymfony/public/:rw
  ##############################
# Certbot Container
##############################
  certbot:
     image: certbot/certbot:latest
     volumes:
       - ./data/certbot/conf:/etc/letsencrypt/:rw
       - ./data/certbotSymfony/conf:/etc/letsencrypt/symfony/:rw
       - ./data/certbotSymfony/www:/var/www/certbot/:rw
     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  db-data:
    driver: local
  web-data:
    driver: local
